class BairrosRepository {
  BairrosRepository();

  List<String> bairros() => [
        'Balneário das Garças',
        'Balneário Remanso',
        'Boca da Barra',
        'Bosque Beira Rio',
        'Bosque da Areia',
        'Bosque da Praia',
        'Cantagalo',
        'Cantinho do Mar',
        'Casa Grande',
        'Centro',
        'Chácara Mariléa',
        'Cidade Beira Mar',
        'Cidade Praiana',
        'Colinas',
        'Costazul',
        'Enseada das Gaivotas',
        'Extensão do Bosque',
        'Extensão Novo Rio das Ostras',
        'Extensão Serramar',
        'Fazenda Palmeiras',
        'Floresta das Gaivotas',
        'Gelson Apicelo',
        'Jardim Bela Vista',
        'Jardim Campomar',
        'Jardim Mariléa',
        'Jardim Miramar',
        'Jardim Patrícia',
        'Liberdade',
        'Loteamento Atlântica',
        'Mar do Norte',
        'Mar Y Lago',
        'Nova Aliança',
        'Nova Cidade',
        'Nova Esperança',
        'Novo Rio das Ostras',
        'Operário',
        'Ouro Verde',
        'Palmital',
        'Parque São Jorge',
        'Parque Zabulão',
        'Peroba',
        'Porto Seguro',
        'Praia Mar',
        'Recanto',
        'Recreio',
        'Reduto da Paz',
        'Residencial Camping do Bosque',
        'Residencial Maria Turri',
        'Residencial Praia Âncora',
        'Residencial Rio das Ostras',
        'Residencial Verdes Mares',
        'Rocha Leão',
        'São Cristóvão',
        'Serramar',
        'Sobradinho Cerveja',
        'Terra Firme',
        'Vila Real',
        'Vila Verde',
        'Village Rio das Ostras',
        'Village Sol e Mar',
      ];
}
