name: cmpop_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'
#The CHANGELOG.md doesn't mention sdk: '>2.10.0, <=2.12.0' with respect to null safety

dependencies:
#  path: ^1.7.0
  uuid: '>=2.2.2 < 3.0.9'
  #http: ^0.13.3 # Null safety
  http: '>=0.12.2 < 0.13.5'
  intl: '>=0.16.1 < 0.17.9'
  http_parser: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
